environment:
  global:
    TWINE_USERNAME: dengwirda

build_script:
  - pip install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
